sudo: false
language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

after_script:
  - cd public
  - git init
  - git config user.name "xwartz"
  - git config user.email "stddup@gmail.com"
  - git add --all
  - git commit -m "pupa forward"
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:gh-pages

os:
  - osx

env:
  global:
    - GH_REF: github.com/xwartz/pupa.git
    - secure: "PysLbVjicuAy2j1mKGYzllCQEvqWOqRHgcNIFyVxc3pnMQ2hWiAGL5aEEQxbsbF37UePTTanyWf/fHiBYIJE/6dOH/Rnn79LX4E3AGbTjF9v0rse85DYWqRUqf6nruewMBRoSPWmCZNEsNg/aQHiRirvLC+RPCLrIxm+83ynY+YO6mFnmseyWlJhm/t+d9cUuD+eCV+58dDcLPq4h049CegCQVRTRjEt4h4KHjz30l//2GHedg8SimDCKKrm/dNAAzfG/mTu1G0qrCd6b0Mgs4yao4WHyOBOGokquqdZroHq5x9dt+YE+L5yl7BqJLwQZmZNU1GGgb4Of58stMMXBM9lN/O2+UpFpDtduRUUvZzeHHPskDh8Y+HQHkWJke6hQ83T85FfjsOWOlOUEdn+WyczrKoBIcDLH1oIcDeApRNdnVgBc7Kvkw6vf4RKKoLTQLbsmcdEOL7aJCZvjNY7KXVhAwoSg8ENIwxWipFDoLZYloPoDGGKQ7deZBcTztIxGRkEn7iWYAEQCjihKZAD3HmrG6dfcsZqVbZNBkbDmAW8rkxR9L+8NXMfMpKr7ePXrEYD5ZipYcAXMbHsk7U5mquzuzCB0P0rA0GSUpDupQ2l+4tIfO2QEqEStn8qRqVm1NcBSy0XipaHixmRyCzxjuYuZu++2p2/xJUrVpNuEwo="
