sudo: false
language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

before_script:
  - git config --global user.name "xwartz"
  - git config --global user.email "stddup@gmail.com"
  # 确保主题是最新的
  - rm -rf themes/nuna
  # clone 博客主题
  - git clone https://${GH_Token}@${GH_THEME} themes/nuna

script:
  # 生成静态文件
  - npm run build

after_script:
  # 将生成的静态文件，初始化为 git 仓库
  - cd public
  - git init
  - git config user.name "xwartz"
  - git config user.email "stddup@gmail.com"
  - git add --all
  - git commit -m "pupa forward"
  # 推送到 gh-pages 分支
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:gh-pages

os:
  - osx

env:
  global:
    # 博客主题仓库
    - GH_THEME: github.com/xwartz/hexo-theme-nuna.git
    # 博客仓库
    - GH_REF: github.com/xwartz/pupa.git
    # 加密的 token
    - secure: "PysLbVjicuAy2j1mKGYzllCQEvqWOqRHgcNIFyVxc3pnMQ2hWiAGL5aEEQxbsbF37UePTTanyWf/fHiBYIJE/6dOH/Rnn79LX4E3AGbTjF9v0rse85DYWqRUqf6nruewMBRoSPWmCZNEsNg/aQHiRirvLC+RPCLrIxm+83ynY+YO6mFnmseyWlJhm/t+d9cUuD+eCV+58dDcLPq4h049CegCQVRTRjEt4h4KHjz30l//2GHedg8SimDCKKrm/dNAAzfG/mTu1G0qrCd6b0Mgs4yao4WHyOBOGokquqdZroHq5x9dt+YE+L5yl7BqJLwQZmZNU1GGgb4Of58stMMXBM9lN/O2+UpFpDtduRUUvZzeHHPskDh8Y+HQHkWJke6hQ83T85FfjsOWOlOUEdn+WyczrKoBIcDLH1oIcDeApRNdnVgBc7Kvkw6vf4RKKoLTQLbsmcdEOL7aJCZvjNY7KXVhAwoSg8ENIwxWipFDoLZYloPoDGGKQ7deZBcTztIxGRkEn7iWYAEQCjihKZAD3HmrG6dfcsZqVbZNBkbDmAW8rkxR9L+8NXMfMpKr7ePXrEYD5ZipYcAXMbHsk7U5mquzuzCB0P0rA0GSUpDupQ2l+4tIfO2QEqEStn8qRqVm1NcBSy0XipaHixmRyCzxjuYuZu++2p2/xJUrVpNuEwo="
